### ISSUE TITLE
Feature `disable_cache_oblivious` not exported

### ISSUE THREAD

**Issue by miried** [tikv/jemallocator#103]
According to the README, "The tikv-jemallocator crate re-exports the [features of the tikv-jemalloc-sys dependency](https://github.com/tikv/jemallocator/blob/master/jemalloc-sys/README.md)".

`tikv-jemalloc-sys` has a feature flag called `disable_cache_oblivious`, but it including it in the `tikv-jemallocator` entry in Cargo.toml leads to an error, because it looks like it does not actually re-export the feature.

Is this intentional? Can the feature be used by including tikv-jemalloc-sys directly in the project? Or does it need to be fixed?

**Comment by BusyJay** [comment]
The doc is not accurate anymore. tikv-jemallocator also has its own features. But yes, it should be more convenient to reexports all tikv-jemalloc-sys' features. I'm open for a pull request.

> Can the feature be used by including tikv-jemalloc-sys directly in the project?

Yes, it is a workaround.
