### ISSUE TITLE
Supported targets table in README and it's meaning

### ISSUE THREAD

**Issue by jaskij** [tikv/jemallocator#24]
I'm looking at README (screenshot below), in the context of `aarch64-unknown-linux-gnu`, and my question is, what does the third column actually mean? To my knowledge, there is no such crate as `tikv-jemalloc`, should this mean `tikv-jemalloc-ctl`? Or does this column mean something else?

I want to use `tikv-jemallocator` in my software, targeting aarch64, but am not sure if it's safe to do so?

![image](https://user-images.githubusercontent.com/1429132/163421944-81864093-10a0-4e23-8285-9ce34614f1a6.png)

**Comment by BusyJay** [comment]
Sorry, it should mean `jemalloc` itself. We only run tests of jemalloc itself on x86_64-unknown-linux-gnu. Although, I believe it should work on `aarch64-unknown-linux-gnu`, TiKV itself also enable jemalloc on the platform.

**Comment by jaskij** [comment]
@BusyJay thanks for the explanation.

I'm not too worried about `jemalloc` itself - [it is packaged by Yocto](https://layers.openembedded.org/layerindex/recipe/190956/) and nothing in the recipe tells me `jemalloc` won't work on aarch64. The timing oddly coincides with the project mainlining Rust support.
