### ISSUE TITLE
install -v not supported on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [tikv/jemallocator#28]
Hi,

`jemalloc-sys` is a crate dependency of several rust packages we provide as native NetBSD packages.
Today I came across the first one that has moved from v0.3.2 to v0.5.0+5.3.0, `fd`, https://github.com/sharkdp/fd

This package used to build successfully with v0.3.2 but now fails since NetBSD install does not support the `-v` option.
The error while building [here](https://pastebin.com/PsvUSr1P).

Any chance you could fix this portability issue and support as many OS's as possible?
Thanks!

**Comment by BusyJay** [comment]
Sorry, I don't have NetBSD installation on hand. This seems probably an issue of jemalloc itself as all jemallocator does is `make install`. Can you verify whether github.com/jemalloc/jemalloc itself can compile on NetBSD?

**Comment by 0323pin** [comment]
> Sorry, I don't have NetBSD installation on hand.

That's fine, I understand it.

> Can you verify whether github.com/jemalloc/jemalloc itself can compile on NetBSD?

jemalloc-5.2.1 is available on our package repository. But, I see it contains a few patches, so this might be the problem, as it will probably not build without those. I need some time to go through the patches and see if they are relevant or not.

**Comment by 0323pin** [comment]
@BusyJay https://github.com/jemalloc/jemalloc/pull/2284
Shall we close this now and hope for a new `jemalloc` release or, shall we keep this open until that's done?

**Comment by 0323pin** [comment]
@BusyJay `jemalloc` has been fixed now. Guess we need a release, unless you want to pull from git HEAD.

**Comment by BusyJay** [comment]
I will wait some time for the new release. Otherwise I will create a patch release in tikv's fork first.

**Comment by 0323pin** [comment]
Thank you!
