### ISSUE TITLE
Use jeprof to see only the address, not the function name.

### ISSUE THREAD

**Issue by silence-coding** [tikv/jemallocator#33]
Use as follows：
```
[dependencies]
jemallocator = { version = "0.5.0", features = ["debug","profiling"] }
jemalloc-sys = { version = "0.5.1+5.3.0-patched", features = ["debug","profiling"] }


use jemalloc_sys::mallctl;
use std::os::raw::{c_char, c_int};
use std::ptr;
fn dump() -> c_int {
    unsafe {
        mallctl(
            "prof.dump\0".as_bytes() as *const _ as *const c_char,
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
            0,
        )
    }
}
```

Output：
```
[root@k8s Server]# jeprof --text /Server/target/release/server  /tmp/jeprof.out.1538428.1.m1.heap
Using local file /Server/target/release/server.
Using local file /tmp/jeprof.out.1538428.1.m1.heap.
Total: 16.5 MB
    16.5 100.0% 100.0%     16.5 100.0% 0x000055f0b64ff4fb
     0.0   0.0% 100.0%      0.5   3.0% 0x000055f0b5752cbc
     0.0   0.0% 100.0%      0.5   3.1% 0x000055f0b5787449
     0.0   0.0% 100.0%      0.5   3.3% 0x000055f0b57881bc
     0.0   0.0% 100.0%      0.5   3.0% 0x000055f0b5792cd6
     0.0   0.0% 100.0%      0.5   3.1% 0x000055f0b57a3e51
     0.0   0.0% 100.0%      0.5   3.1% 0x000055f0b57b1c71
     0.0   0.0% 100.0%     12.3  74.6% 0x000055f0b57b3d89
     0.0   0.0% 100.0%      3.0  18.4% 0x000055f0b5819d1e

```

**Comment by BusyJay** [comment]
Make sure you have built it with debug info. https://doc.rust-lang.org/cargo/reference/profiles.html#debug

**Comment by silence-coding** [comment]
I use the gdb to confirm that the Rust code contains debugging information. I use jeprof to analyze the demo function information, but only memory addresses can be displayed in our service code.

**Comment by silence-coding** [comment]
I want to know what jeprof determines the function information corresponding to memory addresses. I don't want to use gdb to look at memory addresses one by one.

**Comment by BusyJay** [comment]
It's also possible that an outdated version of `jeprof` is used. Some bugs related to symbol resolving have been fixed in the past. It's a perl script, you can check the [source](https://github.com/aerospike/jemalloc/blob/master/bin/jeprof.in).

**Comment by silence-coding** [comment]
Thank you, I can confirm that the latest version of tikv/jemallocator is used.

**Comment by silence-coding** [comment]
Other than that, I have problems with fragmentation and delayed release, is there anything else that can be optimized?

https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md
