### ISSUE TITLE
jemalloc-sys: bundled configure fails for riscv64gc

### ISSUE THREAD

**Issue by bnoctis** [tikv/jemallocator#36]
Hi,

jemalloc-sys currently fails to build from source on Debian (see [buildd logs](https://buildd.debian.org/status/logs.php?pkg=rust-jemalloc-sys)). The cause is that `configure` didn't recognize riscv64gc.

Testing reveals that, when using its `autogen.sh`, jemalloc successfully builds itself. However, with the current setting of this crate's `build.rs`, a bundled, pre-generated `configure` is used, which fails.

Running `autogen.sh` seems trivial, and it's available since jemalloc is submoduled. Is there anything that prevents its use?

**Comment by bnoctis** [comment]
Taking out `build.rs` generated configure args `--host` & `--build` worked around the problem, as configure detected host and build as riscv64, not riscv64gc. Alternatively, adding riscv64gc to `jemalloc/build-aux/config.{sub,guess}` also worked.

**Comment by BusyJay** [comment]
You can check the discussion here: https://github.com/gnzlbg/jemallocator/pull/42#discussion_r185509923. Giving that jemalloc only supports mingw on windows, I think the only reason to use `configure` is to have less dependencies.

**Comment by bnoctis** [comment]
@BusyJay However the bundled configure is itself a dependency - jemalloc itself has a (autoconf generated) configure, why add another?

Anyway, this issue has little to do with the bundled configure. Its main cause remains upstream not recognizing the specific arch.

**Comment by BusyJay** [comment]
> jemalloc already has a (autoconf generated) configure

No, it doesn't when adding as a submodule.

**Comment by bnoctis** [comment]
My mistake. I meant jemalloc already has an autoconf based configure generation script.
