### ISSUE TITLE
Future Incompatibility warning for Rust's beta branch

### ISSUE THREAD

**Issue by mimullin-bbry** [tikv/jemallocator#46]
On March 9th, 2023, Rust will update it's stable branch to 1.68.  When this happens clients of jemallocator will start seeing a warning message upon compiling projects.

```
warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

This warning message stems from jemalloc-sys using fs_extra as a build dependency.  fs_extra has fixed this warning in their github branch, however the project has not published a new release (which would include these changes) since August 25, 2020.

The warning message presented to clients of jemalloc does not represent a "real issue" that "must" be dealt with, however it may start to cause errors in certain CI/CD pipelines.

A ticket has been raised to the fs_extra project (https://github.com/webdesus/fs_extra/issues/68) to request a new release with these fixes, but the fs_extra project does not seem to be very active.  Jemallocator should think about mitigations if fs_extra does not ship a new release before March 9th.

**Comment by BusyJay** [comment]
Should be fixed by #47.
