### ISSUE TITLE
Is it convenient for bumping version to v0.5.3 on crates.io?

### ISSUE THREAD

**Issue by bioinformatist** [tikv/jemallocator#50]
Hey bro, I'v used `tikv-jemallocator` v0.5.0 for custom allocator in our projects for a long time.

The `cargo clippy` bring me notes below these days:

```pre
the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0
```

I noticed that since v0.5.3 `tikv-jemallocator` do not depend on `fs_extra` at all, but this version seems failed published on https://crates.io.

Is there something wrong with CI? Would you mind fix this problem? Thanks in advance.

**Comment by BusyJay** [comment]
Actually we don't have v0.5.3 tikv-jemallocator, instead we only have 0.5.3 tikv-jemalloc-sys. If you have Cargo.lock checked in the version control, it's possible an old version is used. You can update it by `cargo update -p tikv-jemalloc-sys`.

**Comment by bioinformatist** [comment]
Yes, it did solve the problem. Thank you for your reply~
