### ISSUE TITLE
`c_bool` is not (always?) `c_int`, causes miscompilation of extent hook API

### ISSUE THREAD

**Issue by Arnavion** [tikv/jemallocator#53]
https://github.com/tikv/jemallocator/blob/fd00e12cc531d15a52e1ace32ff33eb3366bc5e4/jemalloc-sys/src/lib.rs#L53

This leads to a miscompilation when using API that involves `c_bool`, ie [the extent hook API.](https://github.com/jemalloc/jemalloc/blob/e13ca993e8ccb9ba9847cc330696e02839f328f7/include/jemalloc/jemalloc_typedefs.h.in#L3-L65) For example, when my implementation of [this Rust typedef](https://github.com/tikv/jemallocator/blob/fd00e12cc531d15a52e1ace32ff33eb3366bc5e4/jemalloc-sys/src/lib.rs#L744-L752) wrote to the supposed `c_bool` pointers, it ended up smashing other variables in the caller's stack. I'm using the `x86_64-unknown-linux-musl` and `x86_64-unknown-linux-gnu` targets with gcc 11, gcc 12 and gcc 13.

jemalloc expects to be using C99 `bool` via [the `stdbool.h` header,](https://github.com/jemalloc/jemalloc/blob/e13ca993e8ccb9ba9847cc330696e02839f328f7/include/jemalloc/jemalloc_macros.h.in#L2) and the equivalent of that is Rust's `bool`, not `c_int`. jemalloc does have [this header](https://github.com/jemalloc/jemalloc/blob/e13ca993e8ccb9ba9847cc330696e02839f328f7/include/msvc_compat/C99/stdbool.h) for Windows MSVC that defines it to win32's `BOOL` which is apparently an `int`. I'm not sure if even that is required, since web search seems to indicate MSVC also got `stdbool.h` in VS 2013, but I don't have Windows to check myself.

---

Workaround: Write the extent hook implementations with the correct signature (using Rust `bool`), then transmute then into the incorrect signatures that tikv-jemalloc-sys requires (using `c_int`) via `std::mem::transmute`.

**Comment by BusyJay** [comment]
How about defining `c_bool` conditionally? If it's on MSVC windows, pick `c_int`, otherwise pick `bool`.

**Comment by Arnavion** [comment]
Did you confirm that building on MSVC does indeed use the compat header and not whatever `stdbool.h` MSVC (apparently) aleady ships with?

**Comment by BusyJay** [comment]
No, I don't have any machine that runs Windows. The file is named stdbool.h and get included in the header searching path by configure script, so even MSVC ships one, the former should be used instead.

**Comment by BusyJay** [comment]
Cool, can you send it as a PR?

**Comment by Arnavion** [comment]
#54
