### ISSUE TITLE
Optionally provide jemalloc master? 

### ISSUE THREAD

**Issue by LifeIsStrange** [tikv/jemallocator#6]
Jemalloc 5.2.1 was in 2019 (> 1.5 years ago), since then a lot of performance improvements have been added.
Hence porting the master version of jemalloc in an optional flavor of this crate would enable interesting benchmarking.

**Comment by BusyJay** [comment]
There are many changes between master and 5.2.1, I'm afraid it's not an easy step to migrate to master. I prefer to wait for a new (stable) official release from jemalloc.

**Comment by LifeIsStrange** [comment]
Ok
