### ISSUE TITLE
It seems that Windows platform still has not been supported.

### ISSUE THREAD

**Issue by Nelocage** [tikv/jemallocator#68]
warning: tikv-jemalloc-sys@0.5.4+5.3.0-patched: "jemalloc support for `x86_64-pc-windows-msvc` is untested"
error: failed to run custom build command for `tikv-jemalloc-sys v0.5.4+5.3.0-patch

**Comment by Nelocage** [comment]
rust-rocksdb/rust-rocksdb#155 Not sure if this can be avoided

**Comment by kaliubuntu0206** [comment]
You may see the issue here https://github.com/tikv/jemallocator/issues/22
