### ISSUE TITLE
[profiling] help

### ISSUE THREAD

**Issue by silence-coding** [tikv/jemallocator#7]
Why Is EFAULT Returned During Running When the Profiling Feature Is Enabled?

```
let epoch_name = "prof.dump";
let epoch_c_name = CString::new(epoch_name).unwrap();
mallctl(epoch_c_name.as_ptr(), null_mut(), null_mut(), null_mut(), 0);
```

**Comment by BusyJay** [comment]
Have you set the profile environment variables? A detail instructions can be found at https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling. profiling feature just compiles the functionality, but not enable it by default.

**Comment by silence-coding** [comment]
@BusyJay Thank you for your answer. It has been set before, but it is not recognized.

tikv-jemallocator =  {version = "0.4",  features = ["profiling","stats"]}

When export MALLOC_CONF="prof:true,prof_prefix:jeprof.out" is used.

![image](https://user-images.githubusercontent.com/32766901/112834474-9acf4300-90ca-11eb-8eea-fbc97c2cb065.png)

**Comment by BusyJay** [comment]
If feature `unprefixed_malloc_on_supported_platforms` is not enabled, you should set `_RJEM_MALLOC_CONF` instead of `MALLOC_CONF`.

**Comment by silence-coding** [comment]
@BusyJay Thank you!  It work!!!!!!!!

**Comment by silence-coding** [comment]
I'd like to consult you! I can't see my own method calls, are there any parameters I can set to see more stacks?

![image](https://user-images.githubusercontent.com/32766901/113018734-6daa8f80-91b3-11eb-89d1-7f486cb643ae.png)

**Comment by BusyJay** [comment]
You can export `svg` for better visibility.

**Comment by velvia** [comment]
By the way, I am trying this on 0.5, and the only way I could find to enable the profiling is to set `JEMALLOC_SYS_WITH_MALLOC_CONF` prior to building, and build in the options -- but this is very inflexible.  Instead we'd prefer to use `MALLOC_CONF` (or the prefixed one with `_RJEM_MALLOC_CONF`), but neither one seems to work on Mac OS (I'm on M1 chip).

**Comment by BusyJay** [comment]
@velvia How about send a new issue for the problem?
