### ISSUE TITLE
Allow per-target `JEMALLOC_OVERRIDE` env

### ISSUE THREAD

**Issue by Torrekie** [tikv/jemallocator#90]
While cross-compiling, setting `JEMALLOC_OVERRIDE` could cause failures due to incompatibilities between build and host platforms.

A better solution would be something like [openssl-sys/build/find_normal.rs#L14 ](https://github.com/sfackler/rust-openssl/blob/5095d7da4e26ec06ff29948068430379dac8f5f1/openssl-sys/build/find_normal.rs#L14) which has implementation at [openssl-sys/build/main.rs#L41](https://github.com/sfackler/rust-openssl/blob/5095d7da4e26ec06ff29948068430379dac8f5f1/openssl-sys/build/main.rs#L41), which allows env definitions as a form of `<TARGET_TRIPLE>_ENV` (e.g. `AARCH64_APPLE_DARWIN_MYENV`

**Comment by BusyJay** [comment]
Can you explain more on what "failures" you met?

**Comment by BusyJay** [comment]
I don't get it. You should cross compile for one target at a time, right? So why not just specify the correct `JEMALLOC_OVERRIDE` for each compile?

**Comment by Torrekie** [comment]
rustc itself is using jemalllc-sys, while it compiles build and host toolchain at same time when `host` specified in config.toml, defining env per target is necessary because it was not able to compile host toolchain without compiling a build toolchain (even with rust compilers specified). I think that's why openssl-sys supported per target env, since it was also vendored by official rustc source

**Comment by BusyJay** [comment]
I see. Would you like to send a PR?
